app/urls.py
from django.urls import path
from .views import IndexView, SobreView, ModeloView, MatView, PortView
from . import views
urlpatterns = [
    path('', IndexView.as_view(), name='inicio'),
    path('sobre/', SobreView.as_view(), name='sobre'),
    path('matematica/', views.salvarMatematica, name='matematica'),
    path('portugues/', views.salvarPortugues, name='portugues'),
    path('login/', views.login, name ='login'),
    path('formulario/', views.index, name ='form'),
    path('modelo/', ModeloView.as_view(), name ='modelo'),
    path('portugues/', PortView.as_view(), name='portugues'),
    path('coordenadorias', views.getCoordenadorias, name = "coordenadorias"),
    path('escolas', views.getEscolas, name = "escolas"),
    path('turnos', views.getTurnos, name = "turnos"),
    path('series', views.getSeries, name = "series"),
    path('turmas', views.getTurmas, name = "turmas"),
    path('materias', views.getMaterias, name = "materias")

  #  path('resultado/', views.lista, name='resultado')


]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models
from django.db.models import CASCADE
import mysql.connector

class Professor(models.Model):

    jurisdicao = models.ForeignKey('Jurisdicao', on_delete=CASCADE,verbose_name='Jurisdição')
    coordenadoria = models.ForeignKey('Coordenadoria', on_delete=CASCADE)
    escola = models.ForeignKey('Escola', on_delete=CASCADE)
    turno = models.ForeignKey('Turno', on_delete=CASCADE)
    serie = models.ForeignKey('Serie', on_delete=CASCADE,verbose_name='Série | Ano')
    turma = models.ForeignKey('Turma', on_delete=CASCADE)
    materia = models.ForeignKey('Materia', on_delete=CASCADE,verbose_name='Componente Curricular')
    nome = models.CharField(max_length=50, verbose_name='Nome do Professor')

    def __str__(self):
        return self.nome


class Jurisdicao(models.Model):

    jurisdicao = models.CharField(max_length=20, verbose_name='Jurisdição')

    def __str__(self):
        return self.jurisdicao

class Coordenadoria(models.Model):

    coordenadoria = models.CharField(max_length=50, verbose_name='Coordenadoria')
    #coordenacao = models.CharField(max_length=10)
    jurisdicao = models.ForeignKey(Jurisdicao, on_delete=CASCADE)

    def __str__(self):
        return self.coordenadoria


class Escola(models.Model):

    escola = models.CharField(max_length=100, verbose_name='Escola')
    coordenadoria = models.ForeignKey(Coordenadoria, on_delete=CASCADE)

    def __str__(self):
        return self.escola

class Turno(models.Model):

    turno = models.CharField(max_length=20, verbose_name='Turno')
    escola = models.ForeignKey(Escola, on_delete=CASCADE)

    def __str__(self):
        return self.turno

class Serie(models.Model):

    serie = models.CharField(max_length=20, verbose_name='Série/Ano')
    turno = models.ForeignKey(Turno, on_delete=CASCADE)

    def __str__(self):
        return self.serie


class Turma(models.Model):

    turma = models.CharField(max_length=20, verbose_name='Turma')
    serie = models.ForeignKey(Serie, on_delete=CASCADE)

    def __str__(self):
        return self.turma

class Materia(models.Model):

    materia = models.CharField(max_length=25, verbose_name='Componente Curricular')
    serie = models.ForeignKey(Serie, on_delete=CASCADE)
 
    def __str__(self):
        return self.materia

class Bimestre(models.Model):
    bimestre = models.CharField(max_length=25, verbose_name='Bimestre')
    materia = models.ForeignKey(Materia, on_delete=CASCADE)

    def __str__(self):
        return self.bimestre

class Pergunta(models.Model):
    bimestref = models.ForeignKey('Bimestref', on_delete=CASCADE)
    pergunta = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.pergunta

class Resposta(models.Model):
    resposta = models.BooleanField()
    professor = models.ForeignKey(Professor, on_delete=CASCADE)
    pergunta = models.ForeignKey(Pergunta, on_delete=CASCADE)

    def __str__(self):
        return self.resposta


class Serief(models.Model):

    serie = models.CharField(max_length=20, verbose_name='Série/Ano')

    def __str__(self):
        return self.serie


class Materiaf(models.Model):

    materia = models.CharField(max_length=25, verbose_name='Componente Curricular')
    serief = models.ForeignKey(Serief, on_delete=CASCADE)

    def __str__(self):
        return self.materia

class Bimestref(models.Model):
    bimestre = models.CharField(max_length=25, verbose_name='Bimestre')
    materiaf = models.ForeignKey(Materiaf, on_delete=CASCADE)

    def __str__(self):
        return self.bimestre
#class Escola_professor(models.Model):
 #   escola = models.ForeignKey(Escola, on_delete=CASCADE )
 #   professor = models.ForeignKey(Professor, on_delete=CASCADE)

#class Materia_professor(models.Model):
    #alterar turma para checklist
#    materia = models.ForeignKey(Materias, on_delete=CASCADE)
#    professor = models.ForeignKey(Professor, on_delete=CASCADE)
#    escola = models.ForeignKey(Escola, on_delete=CASCADE)
#    turno = models.ForeignKey(Turno, on_delete=CASCADE)
#    serie = models.ForeignKey(Serie, on_delete=CASCADE)
#    turma = models.ForeignKey(Turma, on_delete=CASCADE)

# construir formulário para a matéria class Matemática(models.Model)

app/templates/materias/series/9ano/matematica/matematica9.html
{% extends 'model.html' %}
{% load static %}

{% block conteudo %}
<center><h1>Formulário do Componente Curricular de Matemática</h1></center>
<br>
<div class="top-buffer">
    <form action="{% url 'matematica' %}" method="post" >
    {% csrf_token %}

    <div style="display: none;">
        <label>professor</label>
            <select name="professor" id="id_professor">
                <option value="{{professor_instance.instance.id}}">{{professor_instance.instance.nome}}</option>
            </select>
        </div>

    <div >

        <div>
            <label>Selecione o Bimestre:</label>
            <select name="bimestre" id="bimestre_id">
                <option value="" data-default disabled selected></option>
                <option value="1">1º Bimestre</option>
                <option value="2">2º Bimestre</option>
                <option value="3">3º Bimestre</option>
                <option value="4">4º Bimestre</option>
            </select>
        </div>
        <br>
        <div>
            <label>Foi possível realizar a coleta?</label>
            <select name="coleta" id="coleta_id" required="required" onclick="testando()">
                <option value="" data-default disabled selected></option>
                <option value="sim"  data-default >Sim</option>
                <option value="nao">Não</option>
            </select>
        </div>
        <br>
        <div id="motivo" style="display:none">
            <label>Se não foi possível, indique o motivo:</label>
            <select name="motivo" id="motivo_id">
                <option value="" data-default disabled selected></option>
                <option value="Escola em Greve">Escola em Greve</option>
                <option value="Escola em Reforma">Escola em Reforma</option>
                <option value="Profissional Ausente">Profissional Ausente</option>
                <option value="Outros">Outros</option>
            </select>
        </div>
        <br>
        <div id="outros" style="display:none">
            <label>Informe o motivo:</label>
            <input type="text" id="id_outros">
        </div>
        <hr>

        <center><h3 id="obj_id" style="display:none">Objetos do Conhecimento</h3></center>

        <table name="bim1" id="bim1_id" style="display:none">
            <tr>
                <td><input type="checkbox" id="p1_id" name="p1" style="width: 25px; height: 25px;"></td>
                <td></td>
                <td></td>
                <td></td>
                <td height="100" align='justify'><label for="p1">NOTAÇÃO CIENTÍFICA: POTENCIAÇÃO DE EXPOENTES INTEIROS.</label></td>
            </tr>

            <tr>
                <td><input type="checkbox" id="p2_id" name="p2" style="width: 25px; height: 25px;"></td>
                <td></td>
                <td></td>
                <td></td>
                <td height="100" align='justify'><label for="p2">POTENCIAÇÃO E RADICIAÇÃO: RESOLUÇÃO E ELABORAÇÃO DE PROBLEMAS SOBRE A RELAÇÃO ENTRE A POTENCIAÇÃO E A RADICIAÇÃO.</label></td>
            </tr>

            <tr>
                <td><input type="checkbox" id="p3_id" name="p3" style="width: 25px; height: 25px;"></td>
                <td></td>
                <td></td>
                <td></td>
                <td height="100" align='justify'><label for="p3">PRINCÍPIO MULTIPLICATIVO DA CONTAGEM/ SOMA DAS PROBABILIDADES DE TODOS OS EVENTOS DE UM ESPAÇO AMOSTRAL: CÁLCULO DE PROBABILIDADE UTILIZANDO O PRINCÍPIO MULTIPLICATIVO.</label></td>
            </tr>

            <tr>
                <td><input type="checkbox" id="p4_id" name="p4" style="width: 25px; height: 25px;"></td>
                <td></td>
                <td></td>
                <td></td>
                <td height="100" align='justify'><label for="p4">VALOR NUMÉRICO DE EXPRESSÕES ALGÉBRICAS: RESOLUÇÃO E ELABORAÇÃO DE PROBLEMAS QUE ENVOLVAM O CÁLCULO DO VALOR NUMÉRICO DE EXPRESSÕES ALGÉBRICAS.
</label></td>
            </tr>

            <tr>
                <td><input type="checkbox" id="p5_id" name="p5" style="width: 25px; height: 25px;"></td>
                <td></td>
                <td></td>
                <td></td>
                <td height="100" align='justify'><label for="p5">ASSOCIAÇÃO DE UMA EQUAÇÃO LINEAR DE 1º GRAU A UMA RETA NO PLANO CARTESIANO.</label></td>
            </tr>

            <tr>
                <td><input type="checkbox" id="p6_id" name="p6" style="width: 25px; height: 25px;"></td>
                <td></td>
                <td></td>
                <td></td>
                <td height="100" align='justify'><label for="p6" >CONGRUÊNCIA DE TRIÂNGULOS E DEMONSTRAÇÕES DE PROPRIEDADES DE QUADRILÁTEROS: DEMONSTRAÇÃO DE PROPRIEDADES DOS QUADRILÁTEROS UTILIZANDO A CONGRUÊNCIA E SEMELHANÇA DE TRIÂNGULOS.</label></td>
            </tr>

        </table>




        <table name="bim2" id="bim2_id" style="display:none">

            <tr>
                <td><input type="checkbox" id="p11_id" name="p11" style="width: 25px; height: 25px;"></td>
                <td></td>
                <td></td>
                <td></td>
                <td height="100" align='justify'><label for="p11">O PRINCÍPIO MULTIPLICATIVO DA CONTAGEM.</label></td>
            </tr>

            <tr>
                <td><input type="checkbox" id="p12_id" name="p12" style="width: 25px; height: 25px;"></td>
                <td></td>
                <td></td>
                <td></td>
                <td height="100" align='justify'><label for="p12">GRÁFICOS DE BARRAS, COLUNAS, LINHAS OU SETORES E SEUS ELEMENTOS CONSTITUTIVOS E ADEQUAÇÃO PARA DETERMINADO CONJUNTO DE DADOS.</label></td>
            </tr>

            <tr>
                <td><input type="checkbox" id="p13_id" name="p13" style="width: 25px; height: 25px;"></td>
                <td></td>
                <td></td>
                <td></td>
                <td height="100" align='justify'><label for="p13">SISTEMA DE EQUAÇÕES POLINOMIAIS DE 1º GRAU: RESOLUÇÃO ALGÉBRICA E REPRESENTAÇÃO NO PLANO CARTESIANO.
</label></td>
            </tr>

            <tr>
                <td><input type="checkbox" id="p14_id" name="p14" style="width: 25px; height: 25px;"></td>
                <td></td>
                <td></td>
                <td></td>
                <td height="100" align='justify'><label for="p14">EQUAÇÃO POLINOMIAL DE 2º GRAU DO TIPO AX² = B.</label></td>
            </tr>

            <tr>
                <td><input type="checkbox" id="p15_id" name="p15" style="width: 25px; height: 25px;"></td>
                <td></td>
                <td></td>
                <td></td>
                <td height="100" align='justify'><label for="p15">CONSTRUÇÕES GEOMÉTRICAS - ÂNGULOS DE 90°, 60°, 45° E 30° E POLÍGONOS REGULARES, UTILIZANDO INSTRUMENTOS DE DESENHO (OU SOFTWARES): CONSTRUÇÃO DE MEDIATRIZ E BISSETRIZ UTILIZANDO SOFTWARES DE GEOMETRIA DINÂMICA E/OU MATERIAIS MANIPULÁVEIS.
</label></td>
            </tr>

            <tr>
                <td><input type="checkbox" id="p16_id" name="p16" style="width: 25px; height: 25px;"></td>
                <td></td>
                <td></td>
                <td></td>
                <td height="100" align='justify'><label for="p16">CONSTRUÇÕES GEOMÉTRICAS - ÂNGULOS DE 90°, 60°, 45° E 30° E POLÍGONOS REGULARES, UTILIZANDO INSTRUMENTOS DE DESENHO (OU SOFTWARES): CONSTRUÇÃO DOS ÂNGULOS NOTÁVEIS 90°, 60°, 45° E 30° E DE POLÍGONOS REGULARES.
</label></td>
            </tr>

        </table>



        <table name="bim3" id="bim3_id" style="display:none">
            <tr>
                <td> 3 bimestre</td>
            </tr>
        </table>



        <table name="bim4" id="bim4_id" style="display:none">
            <tr>
                <td> 4 bimestre</td>
            </tr>
        </table>

    </div>
        <div class="row">
            <button class='btn btn-success' type="submit" style="margin-right: 5px;margin-left:5px; margin-bottom:5px">Salvar</button>
            <a class="btn btn-danger" style="margin-bottom:5px;"  href="{% url 'inicio' %}">Cancelar</a>
        </div>
     </form>
     <script>
         let coleta_field = document.getElementById("coleta_id")
         coleta_field.addEventListener("change", showMotivo)

        function showMotivo(e){
            let motivo_field = document.getElementById("motivo")
            if(e.target.value == "nao"){
                motivo_field.style.display = "block"
            }else{
                motivo_field.style.display = "none"
            }
        }

        let motivo_field = document.getElementById("motivo_id")
        motivo_field.addEventListener("change", showOutros)

        function showOutros(e){
            let outros_field = document.getElementById("outros")
            if(e.target.value == "Outros"){
                outros_field.style.display = "block"
            }else{
                outros_field.style.display = "none"
            }
        }

        let bimestre_field = document.getElementById("bimestre_id")
        bimestre_field.addEventListener("change", showBimestre)

        function showBimestre(e){

            let bim1_table = document.getElementById("bim1_id")
            let bim2_table = document.getElementById("bim2_id")
            let bim3_table = document.getElementById("bim3_id")
            let bim4_table = document.getElementById("bim4_id")
            let obj_field = document.getElementById("obj_id")
            switch(e.target.value){
                case '1' : obj_field.style.display = "block"
                         bim1_table.style.display = "block"
                         bim2_table.style.display = "none"
                         bim3_table.style.display = "none"
                         bim4_table.style.display = "none"
                         break
                case '2' : obj_field.style.display = "block"
                         bim2_table.style.display = "block"
                         bim1_table.style.display = "none"
                         bim3_table.style.display = "none"
                         bim4_table.style.display = "none"
                         break
                case '3' : obj_field.style.display = "block"
                         bim3_table.style.display = "block"
                         bim1_table.style.display = "none"
                         bim2_table.style.display = "none"
                         bim4_table.style.display = "none"
                         break
                case '4' : obj_field.style.display = "block"
                         bim4_table.style.display = "block"
                         bim1_table.style.display = "none"
                         bim2_table.style.display = "none"
                         bim3_table.style.display = "none"
                         break
            }
        }

     </script>


    </div>

{% endblock conteudo %}

{% block scripts %}
{% endblock scripts %}